builds:
  - binary: hookz
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: hookz
    homepage: "https://github.com/devops-kung-fu/hooks"
    tap:
      owner: devops-kung-fu
      name: homebrew-tap
    commit_author:
      name: djschleen
      email: djschleen@gmail.com

checksum:
  name_template: 'checksums.txt'
