project_name: hookz

builds:
  - 
    binary: hookz
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: hookz
    homepage: "https://github.com/devops-kung-fu/hooks"
    tap:
      owner: devops-kung-fu
      name: homebrew-tap
    commit_author:
      name: djschleen
      email: djschleen@gmail.com

checksum:
  name_template: 'checksums.txt'

nfpms:
  - 
    maintainer: DevOps Kung Fu Mafia <admin@dkfm.io>
    description: Manages client side git hooks resulting in the ability to create git action pipelines.
    homepage: https://github.com/devops-kung-fu/hookz
    license: MPL
    formats:
      - deb
      - rpm

snapcrafts:
  - 
    id: hookz
    name: hookz
    summary: 'Manages client side git hooks resulting in the ability to create git action pipelines.'
    description: |
      Have you ever wanted to integrate custom functionality into your code commit and push workflows without using IDE plugins, hacks, or gnarly scripts? We have, and that's why we developed hookz. hookz allows us to do a ton of commit tasks before our code even hits our branches. As you commit and push code to a git based source repository, hookz will trigger scripts, run tasks, or do just about anything for you.

      The best thing? hookz doesn't care what IDE you develop with, what your back end source control system is, or what languages you program in. Operating System? We don't care. We've compiled hookz for every OS and architecture you'd ever want. 
    grade: stable
    confinement: classic
    base: core20

    apps:
      hookz:
        command: hookz
