  hooks:
  - name: "PlantUML Image Generator"
    type: pre-commit
    url: https://github.com/jjimenez/pre-plantuml
    args: [deflate]
  - name: "Post-Commit Echo"
    type: post-commit
    exec: derp
    args: ["Hello World"]
  - name: "Pre-Commit Echo"
    type: pre-commit
    exec: echo
    args: ["Hello World"]
