  hooks:
  - name: "SHS Download"
    type: pre-commit
    url: https://github.com/devops-kung-fu/shs/releases/download/v0.1.1/shs-0.1.1-linux-amd64
    args: []
  - name: "Post-Commit Echo"
    type: post-commit
    exec: derp
    args: ["Hello World"]
  - name: "Pre-Commit Echo"
    type: pre-commit
    exec: echo
    args: ["Hello World"]
