  hooks:
  - name: "Git Pull (Ensure there are no upstream changes that are not local)"
    type: pre-commit
    exec: git
    args: ["pull"]
  - name: "Go Tidy"
    type: pre-commit
    exec: go
    args: ["mod", "tidy"]
  - name: "Update all go dependencies to latest"
    type: pre-commit
    exec: go
    args: ["get", "-u", "./..."]
  - name: "Update all go dependencies to latest"
    type: pre-commit
    exec: go
    args: ["get", "-u", "./..."]
  - name: "Add all changed files during the pre-commit stage"
    type: pre-commit
    exec: git
    args: ["add", "."]

