  version: 2.1.1
  hooks:
    - type: pre-commit
      actions:
        - name: "Git Pull (Ensure there are no upstream changes that are not local)"
          exec: git
          args: ["pull"]
        - name: "Go Tidy (Recursive)"
          script: "
            #!/bin/bash
            echo -e In the script!!!
            for f in $(find . -name go.mod); 
              do (cd $(dirname $f);
                go mod tidy -v); 
            done
            "
        - name: "Update all go dependencies to latest"
          exec: go
          args: ["get", "-u", "./..."]
        - name: "Run gofmt to format the code"
          exec: gofmt
          args: ["-w", "*/*.go"]
        - name: "Add all changed files during the pre-commit stage"
          exec: git
          args: ["add", "."]
    - type: post-commit
      actions:
      - name: "Post Echo"
        exec: echo
        args: ["-e", "Done!"]
