package cmd

// Generated by https://quicktype.io

type Configuration struct {
	Version float64 `json:"version"`
	Hooks   []Hook  `json:"hooks"`
}

type Hook struct {
	Type    string   `json:"type"`
	Actions []Action `json:"actions"`
}

type Action struct {
	Name string   `json:"name"`
	URL  *string  `json:"URL,omitempty"`
	Args []string `json:"args"`
	Exec *string  `json:"exec,omitempty"`
}

//Configuration holds the commit hook definition loaded out of .hookz.yaml
// type Configuration struct {
// 	Hooks []struct {
// 		Name string   `json:"name"`
// 		Type string   `json:"type"`
// 		URL  *string  `json:"url,omitempty"`
// 		Args []string `json:"args"`
// 		Exec *string  `json:"exec,omitempty"`
// 	}
// }
