name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - 
      #   name: Install Snapcraft
      #   uses: samuelmeuli/action-snapcraft@v1
      #   with:
      #     snapcraft_token: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - 
        run: go version
      - 
        name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          artifact-name: hookz.cyclonedx.json
          path: .
          format: cyclonedx-json
      - 
        name: Release SBOM
        uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.cyclonedx.json$"
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5.0.0
        with:
          distribution: goreleaser
          version: ${{ env.GITHUB_REF_NAME }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}

